openapi: 3.0.0
info:
  title: On Air sign API
  version: 1.0.0
servers:
  - url: http://on-air
tags:
  - name: Mode
  - name: Zoom Alert
  - name: Status
paths:
  /api/mode:
    delete:
      tags:
        - Mode
      summary: Set a blank screen
      responses:
        '204':
          description: Successful response
    put:
      tags:
        - Mode
      summary: Choose a display mode
      description: To be displayed unless alert is active
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              Clock:
                value:
                  name: clock
              Random Pixels:
                value:
                  name: random-pixels
      responses:
        '204':
          description: Successful response
  /api/alert/zoom/call:
    put:
      tags:
        - Zoom Alert
      summary: Zoom meeting has started
      responses:
        '204':
          description: Successful response
    delete:
      tags:
        - Zoom Alert
      summary: Zoom meeting has ended
      responses:
        '204':
          description: Successful response
  /api/alert/zoom:
    put:
      tags:
        - Zoom Alert
      summary: Enable automatic "On Air" alert when Zoom call starts
      responses:
        '204':
          description: Successful response
    delete:
      tags:
        - Zoom Alert
      summary: Disable automatic "On Air" alert when Zoom call starts
      responses:
        '204':
          description: Successful response
  /api/status:
    get:
      tags:
        - Status
      summary: Get system status metrics
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
              example:
                mode: clock
                temperature: 24.25
                zoom:
                  alert-active: true
                  call-in-progress: false

