name: Deploy the static files to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Delete script file
      run: |
        rm webapp/run-test-server.sh

    - name: Production app.js location in index.html
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "app.js"
        replace: "https://jackhiggins.ie/on-air/app.js"
        include: "webapp/index.html"
    
    - name: Production web root in app.js
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "webRoot = '.'"
        replace: "webRoot = 'https://jackhiggins.ie/on-air'"
        include: "webapp/app.js"
    
    - name: Production web socket server in app.js
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "webSocketServerAddr =  'on-air.fritz.box'"
        replace: "webSocketServerAddr = window.location.host"
        include: "webapp/app.js"

    - name: Replace version string
      run: |
        sed -i "s/version=latest/version=$GITHUB_SHA/g" webapp/index.html
        sed -i "s/version=latest/version=$GITHUB_SHA/g" webapp/app.js
      env:
        GITHUB_CONTEXT: ${{ github.sha }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./webapp
